const pillars = [
  ['01', 'Accessible to discovery', 'Review crawlability, indexing, rendering and internal links so important pages can be found and understood.'],
  ['02', 'Useful enough to reference', 'Build clear answers, comparisons and original insights. Support claims with evidence, descriptive headings and relevant sources.'],
  ['03', 'Consistent brand context', 'Align the way a brand, its products and its expertise are described across the website and relevant third-party profiles.'],
  ['04', 'Measured over time', 'Track a defined set of questions across selected engines. Record the date, response, source URLs and brand context, then compare changes.'],
];
const stages = [
  { name: 'Discovery', intent: '“What solves this problem?”', action: 'Search-led articles, educational content and AI answer visibility introduce the brand to relevant audiences.', signal: 'Relevant impressions · topic coverage · mentions' },
  { name: 'Consideration', intent: '“Which option fits my needs?”', action: 'Comparison pages, use cases and evidence help people understand the difference between available options.', signal: 'Engaged visits · return visits · content journeys' },
  { name: 'Conversion', intent: '“What should I do next?”', action: 'Focused landing pages, clear calls to action and straightforward forms turn interest into an enquiry or demo request.', signal: 'Enquiries · demo requests · conversion rate' },
  { name: 'Qualification', intent: '“Is this a good fit?”', action: 'Connect enquiry context, campaign source and agreed lead criteria so marketing and sales can prioritise the right conversations.', signal: 'Qualified leads · opportunities · stage progression' },
  { name: 'Nurture & retention', intent: '“How do I get more value?”', action: 'Useful follow-up content, onboarding and lifecycle communication support evaluation, adoption and continued engagement.', signal: 'Follow-up engagement · activation · retention' },
];
export function SearchStrategy() {
  return <>
    <section className="ai-strategy section wrap" id="ai-search">
      <div className="section-top"><p className="eyebrow">02 / AI search & brand discovery</p><p className="section-aside">AIO · AEO · GEO</p></div>
      <div className="strategy-heading"><h2>From being indexed<br/>to being <em>referenced.</em></h2><p>My approach to AI optimization (AIO) connects technical SEO, answer-focused content and brand clarity. Answer engine optimization (AEO) and generative engine optimization (GEO) extend that work to how answers are formed and sources are surfaced. This includes Google AI Overviews and AI Mode, alongside discovery in tools such as ChatGPT, Gemini and Perplexity.</p></div>
      <div className="strategy-pillars">{pillars.map(([number,title,description])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{description}</p></article>)}</div>
      <div className="signal-comparison"><div><p className="eyebrow">TWO SIGNALS. DIFFERENT MEANINGS.</p><h3>A mention is visibility.<br/>A citation is a source.</h3><p>Both matter, but they answer different questions about a brand’s presence in AI-generated responses.</p></div><div className="signal-definitions"><article><span>BRAND MENTION</span><h4>Is the brand part of the answer?</h4><p>A response names the brand or product, with or without a link. Review the surrounding context, accuracy and which competitors appear alongside it.</p><small>Track: mention frequency within a defined prompt set, context and accuracy.</small></article><article><span>AI CITATION</span><h4>Is a page used as a linked source?</h4><p>A response links to a source page. Check whether it cites the brand’s own site or a third-party page discussing the brand, and which claim the source supports.</p><small>Track: cited domains, cited pages and the questions that surface them.</small></article></div></div>
      <div className="measurement-note"><strong>Connect visibility to business evidence.</strong><p>Monitor mentions and citations separately from referral visits, enquiries and qualified leads. Responses vary by engine, prompt and time; a mention or citation alone does not establish traffic or revenue attribution.</p></div>
      <p className="source-note">For Google’s AI search experiences, SEO fundamentals remain relevant. <a href="https://developers.google.com/search/docs/appearance/ai-features" target="_blank" rel="noreferrer">Google Search guidance ↗</a></p>
    </section>
    <section className="funnel section" id="funnel"><div className="wrap"><div className="section-top"><p className="eyebrow">03 / Marketing & sales funnel</p><p className="section-aside">Discovery is the beginning.</p></div><div className="strategy-heading"><h2>Attention needs<br/><em>a next step.</em></h2><p>I connect search intent, content, landing pages and measurement across the customer journey. Each stage has a different question to answer—and a different signal to measure.</p></div><div className="funnel-steps">{stages.map((stage,index)=><article key={stage.name}><div className="funnel-stage"><span>0{index+1}</span><h3>{stage.name}</h3><p>{stage.intent}</p></div><div className="funnel-action"><p>{stage.action}</p><small>{stage.signal}</small></div></article>)}</div><p className="funnel-footnote">People may revisit or skip stages. The funnel is a planning framework; attribution needs consistent analytics, campaign tagging and CRM context.</p></div></section>
  </>;
}
